GRANT USAGE ON SCHEMA public TO gastos_user;
GRANT CREATE ON SCHEMA public TO gastos_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO gastos_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO gastos_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO gastos_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO gastos_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO gastos_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT EXECUTE ON FUNCTIONS TO gastos_user;
